### ISSUE TITLE
fromJson methods documentation / examples

### ISSUE THREAD

**Issue by castaway** [DinoLeung/TeleDart#136]
## Is your feature request related to a problem?
Kinda - I don't understand how to use the fromJson methods, eg the one for ReplyKeyboardMarkup, I assumed it would take a json string, instead it takes a Map<String, dynamic>, what keys are expected in that?

## Describe the solution you'd like
Add some doc examples of how the fromJson methods can be called

**Comment by DinoLeung** [comment]
Hi @castaway

I am interested to know what you are trying to do with the `fromJson` factory.

Teledart uses [json_annotation](https://pub.dev/packages/json_annotation) to serialse data received from telegram api end points, and the acualy `fromJson` factory implementation is generated by [json_serializable](https://pub.dev/packages/json_serializable) which takse a decoded json data (see also [jsonDecode](https://api.dart.dev/stable/2.9.2/dart-convert/jsonDecode.html)). If you would like to know how the use the factory, you can follow the simplest usage in `telegram.dart` below.
https://github.com/DinoLeung/TeleDart/blob/350f8247a180287911ca28178b9fc78972352e46/lib/src/telegram/telegram.dart#L130

If you are creating a object, it s recommanded to use the default constructor instead of the factory.

**Comment by castaway** [comment]
hey.. I was looking for a less wordy way of making keyboards.. turns out it was easier than I thought eventually, so I did use the normal constructor.

Nevertheless some docs for this saying what its for etc would be useful imo
