### ISSUE TITLE
Garbage collection? Memory increase

### ISSUE THREAD

**Issue by allasca** [DinoLeung/TeleDart#258]
I build telegram bot on ubuntu and compile it. I have 5 bot. and memory always increase when the bot send message to the client.
apo_mg_bot send more message then others.
![image](https://raw.githubusercontent.com/allasca/allasca.github.io/main/source/img/Screenshot%202023-10-27%20010303.png)
and I check on devtool, list 4 top class memory always increase.
![x](https://raw.githubusercontent.com/allasca/allasca.github.io/main/source/img/Screenshot%202023-11-01%20042918.png)

**Comment by DinoLeung** [comment]
@allasca garbage collection is done automatically in dart's runtime, in most cases we don't really need to retard the built-in behavior. Looking at the second image you posed, the app using up about 30MBs of memory seems to be the normal amount to me. Would be good if you could share some trend data so we can better understand it. Also note the `Message` objects are usually bigger because 1. it has more attributes; 2. it has more functions. if the message body is bigger the overall size of the object increase proportionally.
