### ISSUE TITLE
onCallbackQuery not called

### ISSUE THREAD

**Issue by riccardocescon** [DinoLeung/TeleDart#266]
## Describe the bug
I am sending a message with InlineKeyboardButtons and everything works.
When the user taps on a button, i ame editing the message and asks for a user message.
When i receive that message, i am sending a new reply with the same replyMark i had at the beginning (not the same instance, i am calculating it again)
Then every button is not working.
The  teleDart.onCallbackQuery() is not emitting any state

## To Reproduce
- Send a reply with some InlineKeyboardButtons
- When tapping on a button, edit the message (with no InlineKeyboardButtons this time)
- when the user sends a message, send a new reply with the old TeleDartMessage
- Press a button and see nothing emitted / work

## Expected behavior
When tapping the button the second time it should re-do the same thing it did on the first try

## Additional context
To reproduce example: https://github.com/riccardocescon/beer_game_manager_bot/commit/30588996cbe36460ce87c9d6dcbef0f1220ad9a3

create a file .env and add the bot token with the key: BOT_TOKEN
when the bot is running:
- As first command write: /config
- Tap on 'Poll Duration'
- Write '00:00:23'
- Wait for the new message to appear
- Tap again the poll Duration, it will do nothing

**Comment by HeySreelal** [comment]
Hey @riccardocescon , thanks for raising this issue. I've gone through the shared repo code. It seems like this is not an issue with the TeleDart library, instead there is a key logical mistake in your code.

I can see that in `callbackQueryStreamer` method, you are looping through the `teleDart.onCallbackQuery()` to process the incoming callback queries. After you process the first callback query, the return statement in [line number 61](https://github.com/riccardocescon/beer_game_manager_bot/blob/main/lib/beer_game_manager_bot.dart#L61) is reached and the whole method completes there.

Change the `return` statement to a `continue` statement since you're inside the loop and to continue processing the upcoming queries.

The same happens for [line number 31](https://github.com/riccardocescon/beer_game_manager_bot/blob/30588996cbe36460ce87c9d6dcbef0f1220ad9a3/lib/beer_game_manager_bot.dart#L31) inside the `messageStreamer` method.

Hope this helps!

**Comment by riccardocescon** [comment]
Hi, thank you for your answer!
You are right! 
There is no issue with the library, thank you!
