### ISSUE TITLE
send media function

### ISSUE THREAD

**Issue by dev8tg** [DinoLeung/TeleDart#63]
Function to send all types of media from *File Id* 
`send_media` function short a lot if things
send photos, videos, audios, sticker .. etc from telegram file id

**Comment by DinoLeung** [comment]
@dev8tg not sure what do you mean. Do you mean this input media issue #9 ?

**Comment by dev8tg** [comment]
no no, it is not a function from [telegram api](https://core.telegram.org/bots/api)
it is *separate function* - extra functions in the core to make it practical and better :)

**Info:**
Send any media stored on the Telegram servers using a file_id.
This convenience method works with any valid file_id only. It does the same as calling the relevant method for sending media using a file_id, thus saving you from the hassle of using the correct method for the media the file_id is pointing to.

Same Function in other core [HERE](https://docs.pyrogram.org/api/methods?highlight=send_cach#pyrogram.Client.send_cached_media)

**Comment by DinoLeung** [comment]
This can be achieve by `Telegram.sendMediaGroup()` or `TeleDart.replyMediaGroup()`, see the example below. According to Telegram docs, it can take photos and videos.
If you wanted to truly send files dynamically, we will need 2 api calls in total in order to send 1 media, [getFile](https://core.telegram.org/bots/api#getfile) and [sendPhoto](https://core.telegram.org/bots/api#sendphoto) say you are sending a photo for example, which is not ideal. I reckon the file `type` should be saved along with `file_id`.
I probably would not implement this unless there are more requests.

```
  teledart
      .onMessage(keyword: 'test')
      .listen((message) => teledart.replyMediaGroup(message, [
            InputMedia(
                type: 'photo',
                media:'YOUR_FILE_ID')
          ]));
```
