### ISSUE TITLE
instrutions

### ISSUE THREAD

**Issue by paulobreim** [DinoLeung/TeleDart#82]
Hi dino,

I am trying to contact you my e-mail, but the e-mail in flutter dino@330z.net does not exists.

I am trying to port my telegram bot (today in ruby) to dart using your lib.
What version of flutter must be use?
I am using stable and when I open your example in the vscode, the packages:
import 'package:teledart/teledart.dart';
import 'package:teledart/telegram.dart';
import 'package:teledart/model.dart';
show as Target URI not found.

Thank you,
Paulo

**Comment by DinoLeung** [comment]
Thanks for reaching @paulobreim Sorry for the inconvenience, I have forgotten to renew the domain a couple weeks back, but it should be good now. 😆 

In order to use Teledart, Flutter SDK is not required. The library is developed using the latest stable releast of Dart (currently 2.7), and it is recommanded to develop bots with it. In theory you should be able to get away with 2.2.

Just to remember, before you importing the library in your application, make sure to add library name and version number to your `dependancy` section of `pubspec.yaml` like so:
```
dependencies:
  teledart: ^0.0.36
```

If you want to run the example bot, you should be able to just execute `dart example/TeleDart_example.dart` from the project root. If you are after a more comprehansive example, check out https://github.com/DinoLeung/DartWiseBot. It should give you a good idea of how to constructe a Telegram bot in Dart

Hope I have clear up some confusion out of your head. Feel free to reach again if you have any other issues, if it is related to this library I would prefer you to start an issue on this repo.
